import sqlite3
import os
import re
from datetime import datetime

DB_PATH = 'bookmarks.db'
EXPORT_DIR = 'exports/borg_intelligence'

def slugify(text):
    text = text.lower()
    text = re.sub(r'[^\w\s-]', '', text)
    return re.sub(r'[-\s]+', '_', text).strip('-_')

def export_intelligence():
    if not os.path.exists(EXPORT_DIR):
        os.makedirs(EXPORT_DIR)

    if not os.path.exists(DB_PATH):
        print("Database not found.")
        return

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    print("Fetching Borg Intelligence for export...")
    cur.execute('''
        SELECT * FROM bookmarks 
        WHERE research_level = 'borg'
    ''')
    rows = cur.fetchall()
    
    print(f"Exporting {len(rows)} technical dossiers...")
    
    count = 0
    for row in rows:
        title = row['short_description'] or row['url']
        filename = f"{slugify(title[:50])}.md"
        filepath = os.path.join(EXPORT_DIR, filename)
        
        # Build Markdown content
        md = f"""# {title}

## 📋 Metadata
- **Category**: {row['category']}
- **Innovation Score**: {row['innovation_score']}/10
- **Researched At**: {row['created_at']}
- **Source**: [{row['url']}]({row['url']})

## 🧠 Technical Summary
{row['long_description']}

## 🛠️ Key Features
{row['main_features']}

## 🏷️ Tags
{', '.join(['#' + t.strip() for t in (row['tags'] or "").split(',') if t.strip()])}

---
*Generated by Bobby's Research Command v0.1.0*
"""
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(md)
        
        count += 1
        if count % 100 == 0:
            print(f"Exported {count}/{len(rows)}...")

    conn.close()
    print(f"Export complete. {count} dossiers created in {EXPORT_DIR}")

if __name__ == "__main__":
    export_intelligence()
