
import os

links = [
    ('https://docs.roocode.com/roo-code-cloud/roomote-control', 'AI Agents & Frameworks', 'Roo Code Cloud Overview', 'Autonomous cloud agents that plan, code, and fix issues directly from GitHub PRs, Slack, or browsers, independent of local editors.', 'agentic-coding, cloud-agents, roo-code, autonomous-workflows', 'Cloud Agents, Task Sync, Shared Agents, Centralized Billing, Usage Analytics.'),
    ('https://github.com/robertpelloni/metamcp', 'MCP', 'MetaMCP Aggregator & Proxy', 'A robust MCP proxy that orchestrates multiple MCP servers within a single Docker container, providing a unified authenticated gateway.', 'mcp, orchestrator, middleware, proxy, docker', 'Multi-server Aggregation, Namespace Management, Security Middleware, OIDC Auth, Built-in Inspector.'),
    ('https://github.com/The-Pocket/PocketFlow-Tutorial-Cursor/blob/main/blog.md', 'Guides & Articles', 'Building Cursor with Cursor Tutorial', 'A step-by-step guide to building a custom AI coding agent using the minimalist Pocket Flow framework (approx. 100 lines of code).', 'tutorial, agent-architecture, pocket-flow, llm-framework', 'Node-based Logic, Flow Graphs, Shared Store, Tool Selection Logic, Code Editing Sub-flows.'),
    ('https://github.com/OpenHands/OpenHands/blob/f7cb2d0f64666e1f090a5152d7c002aa6f28caf9/openhands/controller/agent_controller.py#L771', 'AI Agents & Frameworks', 'OpenHands Agent Controller Logic', 'Reference implementation of an agent\'s main execution loop, handling state updates, budget limits, and action invocation.', 'openhands, source-code, agent-loop, state-management', 'Iteration Limit Checks, Budget Enforcement, Stuck Detection, LLM Action Invocation.'),
    ('https://benhouston3d.com/blog/building-an-agentic-code-from-scratch', 'Guides & Articles', 'Building an Agentic Coder Blog', 'A deep dive into the development of MyCoder.ai, detailing the evolution from simple chat to highly autonomous coding swarms.', 'blog, mycoder-ai, agent-development, autonomous-coding', 'Seed AI Pattern, Smart Shell, textEditor Logic, SubAgent Delegation, Validation Triangulation.'),
    ('https://simonwillison.net/2025/Oct/5/parallel-coding-agents/', 'Guides & Articles', 'Parallel Coding Agent Lifestyle', 'Simon Willison\'s overview of using multiple AI instances simultaneously for maintenance, research, and isolated implementation tasks.', 'blog, parallel-agents, productivity, simon-willison', 'Agent Scouting, Isolated Checkouts, Risk Management, Multi-Agent Toolkit.'),
    ('https://www.reddit.com/r/ClaudeAI/comments/1pg2nz9/i_have_gemini_cli_working_basically_as_a_subagent/', 'Guides & Articles', 'Gemini CLI as Sub-agent Discussion', 'Reddit community discussion on integrating Gemini CLI as a specialized sub-agent for Claude to handle high-context research tasks.', 'reddit, sub-agents, gemini-cli, claude-skills', 'Custom Claude Skills, System Prompt Tweaking, Context Injection Patterns.'),
    ('https://agentclientprotocol.com/overview/agents', 'AI Agents & Frameworks', 'ACP Agent Directory', 'A comprehensive list of AI agents and coding assistants compatible with the Agent Client Protocol (ACP) standard.', 'acp, agent-directory, interoperability, standards', 'Multi-agent Compatibility, Client-Server Protocol, Industry Standards.'),
    ('https://phil65.github.io/llmling-agent/cli/', 'AI Agents & Frameworks', 'llmling-agent CLI', 'A Python-based CLI for managing AI agents defined in YAML, featuring interactive REPLs and full ACP server support.', 'cli, python, llmling, acp, yaml-config', 'Multi-agent Pools, Resource Management, ACP Serving, Interactive REPL, Toolsets.'),
    ('https://www.reddit.com/r/GithubCopilot/comments/1phnj0e/if_you_think_copilots_context_window_is_too_small/', 'Guides & Articles', 'Copilot Context Expansion Workflow', 'Reddit thread exploring techniques to orchestrate Copilot for larger project context using external tools and sub-agent patterns.', 'reddit, github-copilot, context-window, orchestration', 'Copilot-Orchestra, Context Mining, Custom Instruction Sets.'),
    ('https://pastebin.com/LVvW6ujj', 'Guides & Articles', 'Subagent Orchestrator Instructions', 'A rigid operational framework for an AI "Project Manager" agent that delegates all technical work to research and implementation sub-agents.', 'instructions, prompt-engineering, orchestration, sub-agents', 'Research vs Implementation Handoffs, Mandatory Specs, Context Refresh Patterns.'),
    ('https://developers.googleblog.com/architecting-efficient-context-aware-multi-agent-framework-for-production/', 'Guides & Articles', 'Production Multi-Agent Architecture', 'Google\'s technical breakdown of context engineering and tiered memory systems for high-density multi-agent frameworks.', 'google-blog, architecture, context-engineering, multi-agent', 'Context Compaction, Narrative Casting, Scoped Handoffs, Durable Sessions.'),
    ('https://github.com/a2aproject/A2A', 'AI Agents & Frameworks', 'A2A (Agent-to-Agent) Protocol', 'An open-source communication protocol (via Linux Foundation) enabling diverse AI agents to discover, negotiate, and collaborate.', 'a2a, protocol, linux-foundation, interoperability', 'Agent Discovery, Agent Cards, JSON-RPC Communication, Opacity Preservation.'),
    ('https://www.reddit.com/r/opencodeCLI/comments/1pkki12/swarm_of_80_opencode_subagents_just_generated_the/', 'Guides & Articles', 'OpenCode Swarm Discussion', 'Discussion on running high-volume agent swarms (up to 80 sub-agents) using the OpenCode CLI for massive code generation tasks.', 'reddit, opencode, swarms, multi-agent', 'Swarm Coordination, BMAD Method, Quint-Code Strategy.'),
    ('https://docs.docker.com/ai/mcp-catalog-and-toolkit/toolkit/', 'MCP', 'Docker MCP Toolkit', 'A Docker Desktop management interface for containerized MCP servers, simplifying setup and ensuring secure, isolated tool execution.', 'docker, mcp, security, containerization', 'Integrated Catalog, Profile Organization, Profile Handoffs, Automated Authentication.'),
    ('https://docs.docker.com/ai/mcp-catalog-and-toolkit/dynamic-mcp/', 'MCP', 'Dynamic MCP Discovery', 'Docker\'s documentation on "primordial" management tools that allow agents to find and install MCP servers on-demand during a session.', 'docker, mcp, dynamic-tools, on-demand', 'mcp-find, mcp-add, Sandbox Code Mode, Session-specific Tools.')
]

with open('processed.txt', 'a', encoding='utf-8') as f:
    for link in links:
        f.write(f'{link[0]}, {link[1]}, {link[2]}, {link[3]}, {link[4]}, {link[5]}\n')
