
import os

links = [
    ('https://docs.docker.com/ai/mcp-catalog-and-toolkit/catalog/', 'MCP', 'Docker MCP Catalog', 'A curated collection of 200-300+ verified MCP servers packaged as Docker images for isolated, secure execution.', 'docker, mcp, catalog, containerization', 'Verified Servers, Isolated Execution, Docker Desktop Integration, Autonomous Discovery.'),
    ('https://www.verdent.ai/', 'AI Agents & Frameworks', 'Verdent AI', 'An AI-native partner for software development that utilizes multiple parallel agents to handle complex codebase planning and execution.', 'agentic-coding, parallel-agents, development-partner', 'Parallel Planning, Codebase Awareness, Peer-level Interaction.'),
    ('https://docs.anythingllm.com/agent/custom/developer-guide', 'Guides & Articles', 'AnythingLLM Custom Agent Guide', 'A comprehensive guide for developers to build custom skills for AnythingLLM agents using Node.js and a structured plugin system.', 'anything-llm, developer-guide, custom-skills, node-js', 'Plugin Architecture, Action Definitions, Parameter Schemas, Entrypoint Logic.'),
    ('https://docs.anythingllm.com/agent/custom/plugin-json', 'Guides & Articles', 'AnythingLLM Plugin JSON Spec', 'Technical documentation for the plugin.json configuration file used to define custom agent skills in AnythingLLM.', 'anything-llm, specification, plugin-json, config', 'Action Array, Parameter Types, Metadata, Versioning.'),
    ('https://github.com/cluesmith/codev', 'AI Agents & Frameworks', 'Codev (cluesmith)', 'A development framework and "operating system" built on the SPIR protocol to facilitate high-bandwidth human-AI collaboration.', 'codev, spir, ai-collaboration, development-framework', 'SPIR Integration, Context Portals, Task Orchestration, Self-hosted Development.'),
    ('https://gist.github.com/gc-victor/1d3eeb46ddfda5257c08744972e0fc4c', 'Guides & Articles', 'Orchestrator Agent Creation Guide', 'A GitHub Gist providing detailed patterns for creating orchestrator agents that analyze requests and delegate to specialized sub-agents.', 'gist, orchestrator, sub-agents, prompt-engineering', 'YAML Frontmatter, Routing Logic, Sequential/Parallel Patterns, Context Hygiene.'),
    ('https://github.com/4regab/TaskSync', 'AI Agents & Frameworks', 'TaskSync', 'A tool for integrating human-in-the-loop feedback into AI-assisted development via VS Code, terminal, and MCP.', 'tasksync, human-in-the-loop, feedback, copilot', 'Prompt Queue, Terminal Protocol, Feedback Tool, Agent Autonomy.'),
    ('https://github.com/4regab/TaskSync/blob/main/Prompt/tasksync-v5.2.md', 'Guides & Articles', 'TaskSync V5 Protocol', 'Protocol specification for autonomous terminal agents, defining strict execution rules and feedback loops.', 'protocol, agent-prompt, autonomous-terminal', 'Rule Enforcement, Execution Flow, Status Monitoring.'),
    ('https://github.com/4regab/TaskSync/blob/main/Prompt/specs-tasksync.md', 'Guides & Articles', 'TaskSync Spec Workflow', 'Documentation of a structured specification creation workflow for feature development with AI agents.', 'workflow, specs, planning, documentation', 'Requirement Clarification, Task Breakdown, Verification Steps.'),
    ('https://github.com/4regab/tasksync-mcp', 'MCP', 'TaskSync MCP Server', 'An MCP server that allows AI agents to receive real-time instructions and feedback from the user during development sessions.', 'mcp, tasksync, feedback, real-time', 'Instruction Injection, Feedback Channel, SDK Integration.'),
    ('https://github.com/rayai-labs/agentic-ray', 'AI Agents & Frameworks', 'Superserve (formerly agentic-ray)', 'A production platform for deploying AI agents in isolated Firecracker microVMs with persistent workspaces and credential governance.', 'deployment, microvms, superserve, agent-infrastructure', 'Isolated Sessions, /workspace Persistence, Credential Proxy, Framework Agnostic.'),
    ('https://github.com/biagruot/agentdepot-agents', 'AI Agents & Frameworks', 'AgentDepot Community Database', 'Community-curated database of AI coding agent definitions for Cursor, Windsurf, and Claude Code.', 'directory, coding-agents, community-contributed', 'Multi-tool Support, TS Schema Definitions, Automated Sync.'),
    ('https://github.com/vstorm-co/pydantic-deepagents', 'AI Agents & Frameworks', 'Pydantic Deep Agents', 'A modular Python framework for building autonomous agents with task planning and persistent memory using Pydantic-AI.', 'pydantic-ai, autonomous-agents, python-framework', 'Context Summarization, Budget Tracking, Subagent Delegation, Research UI.'),
    ('https://github.com/denniszielke/agentic-playground', 'AI Agents & Frameworks', 'Agentic Playground Patterns', 'A comprehensive collection of agent orchestration patterns including ReAct, Society of Agents, and graph-based interactions.', 'patterns, langgraph, llamaindex, orchestration-examples', 'Society of Agents, Graph UI, Multimodal Reasoning, MCP Integration.'),
    ('https://github.com/anthropics/anthropic-sdk-typescript/tree/main/examples', 'Guides & Articles', 'Anthropic TS SDK Examples', 'Official foundational examples for the Claude Agent SDK, demonstrating basic agent loops and tool usage in TypeScript.', 'anthropic, typescript, official-examples, mcp', 'Basic Agent Loop, Tool Definitions, MCP Client Setup.'),
    ('https://github.com/anthropics/anthropic-sdk-python/tree/main/examples', 'Guides & Articles', 'Anthropic Python SDK Examples', 'Official foundational examples for the Claude Agent SDK in Python, covering autonomous loops and orchestration patterns.', 'anthropic, python, official-examples, mcp', 'Pythonic Agent Loops, Orchestrator Patterns, MCP Integration.'),
    ('https://github.com/anthropics/claude-agent-sdk-demos', 'Guides & Articles', 'Claude Agent SDK Demos', 'Comprehensive demo applications including research agents, email assistants, and resume generators built with the Claude Agent SDK.', 'demos, full-apps, agent-sdk, use-cases', 'Research Agent, Email Assistant, WebSocket Chat UI, Resume Generator.'),
    ('https://github.com/a2aproject', 'AI Agents & Frameworks', 'A2A Project Organization', 'The GitHub organization hosting the A2A (Agent-to-Agent) protocol and its related tools and implementations.', 'organization, a2a, protocol, standards', 'Protocol Spec, Reference Implementations, Tooling.'),
    ('https://github.com/anthropics/anthropic-sdk-typescript/blob/main/examples/mcp-agent.ts', 'Guides & Articles', 'TS MCP Agent Example', 'Specific example of a TypeScript-based agent using the Model Context Protocol to access external tools.', 'anthropic, typescript, mcp, example', 'MCP Tool Calling, Client Initialization, Error Handling.'),
    ('https://github.com/anthropics/anthropic-sdk-typescript/blob/main/examples/mcp-agent-orchestrator.ts', 'Guides & Articles', 'TS MCP Orchestrator Example', 'TypeScript example showing how to orchestrate multiple MCP-capable agents for complex tasks.', 'anthropic, typescript, orchestration, mcp', 'Multi-agent Handoffs, Shared Context, Task Decomposition.')
]

with open('processed.txt', 'a', encoding='utf-8') as f:
    for link in links:
        # Simple CSV format consistent with existing entries
        f.write(f'{link[0]}, {link[1]}, {link[2]}, {link[3]}, {link[4]}, {link[5]}\n')
