
import os

links = [
    ('https://github.com/SaladDay/cc-switch-cli', 'AI Agents & Frameworks', 'cc-switch-cli', 'A CLI tool for managing and switching between AI CLI tool profiles and providers.', 'cli, cc-switch, profile-manager, ai-tools', 'Profile switching, Environment management, Provider config.'),
    ('https://github.com/Dianel555/gemini-superclaude-mcp-server', 'MCP', 'Gemini SuperClaude MCP', 'An advanced MCP server providing SuperClaude Framework compatibility for the Gemini CLI with 14 expert agents.', 'mcp, superclaude, gemini-cli, orchestration', '22 Specialized Commands, Business Panel, 14 Expert Agents, Behavioral Modes.'),
    ('https://github.com/SuperClaude-Org/SuperClaude_Framework', 'AI Agents & Frameworks', 'SuperClaude Framework', 'A meta-programming framework transforming Claude Code into a high-performance development platform.', 'superclaude, claude-code, framework, orchestration', '30 Slash Commands, 16 Specialized Agents, Deep Research (v4.2), 7 Behavioral Modes.'),
    ('https://github.com/Piebald-AI/splitrail', 'Development Tools & Libraries', 'Splitrail Token Tracker', 'Fast Rust tool for real-time token usage and cost tracking across AI coding CLIs.', 'token-tracking, cost-management, rust, mcp', 'Real-time tracking, Cross-machine aggregation, VS Code extension, MCP Server integration.'),
    ('https://github.com/awesome-opencode/awesome-opencode', 'Guides & Articles', 'Awesome OpenCode', 'Curated collection of resources, plugins, and extensions for the OpenCode terminal AI agent ecosystem.', 'awesome-list, opencode, plugins, ecosystem', 'Plugin Directory, Custom Agents, GUI/TUI frontends, Telemetry tools.'),
    ('https://www.dropstone.io/features', 'AI Agents & Frameworks', 'Dropstone Platform Features', 'AI platform with infinite context, trajectory search, and multi-agent swarm architecture for large codebases.', 'dropstone, orchestration, agent-swarms, enterprise', 'Horizon Mode (10k+ paths), Self-Verifying Code, PIP Interface, Figma/Windows MCP.'),
    ('https://github.com/github/awesome-copilot', 'Guides & Articles', 'Awesome GitHub Copilot', 'Community-driven list of resources, custom agents, and plugins to extend GitHub Copilot.', 'awesome-list, github-copilot, plugins, mcp', 'Custom Instructions, Agent Workflows, MCP server directory, Community scripts.'),
    ('https://tidewave.ai/blog/claude-code-codex', 'Guides & Articles', 'Tidewave Claude/Codex Integration', 'Integration of Claude Code and OpenAI Codex into a full-stack browser environment using ACP and MCP over WebSockets.', 'blog, tidewave, claude-code, acp', 'ACP/MCP over WebSockets, Deep Framework Access, Browser-based IDE.'),
    ('https://github.com/milisp/opencode-gui', 'Development Tools & Libraries', 'OpenCode GUI', 'Lightweight Tauri desktop application providing a graphical chat interface for local OpenCode servers.', 'opencode, gui, tauri, desktop-app', 'Local Server Connection, Project Directory Config, Chat UI.'),
    ('https://github.com/chris-tse/opencode-web', 'Development Tools & Libraries', 'OpenCode Web', 'Web-based frontend designed to manage and visualize OpenCode AI agents with real-time collaboration.', 'opencode, web-ui, collaboration, visualization', 'Real-time Logs, Agent Orchestration UI, Web Deployment.'),
    ('https://opencode.ai/docs/plugins/', 'Guides & Articles', 'OpenCode Plugin Docs', 'Documentation for extending OpenCode via hooks, tools, and custom configurations using Bun runtime.', 'opencode, plugins, documentation, extensibility', 'NPM Package support, Tool Hooks, Session Management, Event Subscription.'),
    ('https://github.com/slashtechno/amped', 'Development Tools & Libraries', 'Amped Account Switcher', 'Go-based CLI utility for seamlessly switching between multiple accounts for Amp and Claude Code.', 'cli, account-switcher, claude-code, go', 'Secure Credential Storage, Multi-Account Switching, Automatic Service Context.'),
    ('https://github.com/slopus/happy', 'Development Tools & Libraries', 'Happy Remote Agent', 'Mobile and web client providing secure remote access and push notifications for Claude Code and Codex.', 'remote-access, mobile-app, claude-code, security', 'End-to-End Encryption, Instant Device Switching, Push Notifications, Voice Support.'),
    ('https://github.com/2mawi2/schaltwerk', 'AI Agents & Frameworks', 'Schaltwerk ADE', 'Terminal interface using git worktrees to run multiple agentic coding CLIs for spec-driven development.', 'terminal-ui, orchestration, git-worktrees, parallel-agents', 'Dual-terminal Setup, MCP Orchestration, Conflict-free branches.'),
    ('https://github.com/steipete/claude-code-mcp', 'MCP', 'Claude Code MCP Server', 'MCP server that runs Claude Code in one-shot mode, bypassing permissions for automated shell/file tasks.', 'mcp, claude-code, automation, tool-offloading', 'Permission Bypassing, Command Queuing, Cross-Model Offloading, Shell Execution.'),
    ('https://github.com/brwse/claude-tools-mcp', 'MCP', 'Claude Tools MCP Server', 'MCP server securely exposing Claude Code tools over HTTP for remote AI agents.', 'mcp, tools, file-operations, shell-execution', 'Shell Execution with timeout, File offsets/replacement, Glob Search, Security Validation.')
]

with open('processed.txt', 'a', encoding='utf-8') as f:
    for link in links:
        f.write(f'{link[0]}, {link[1]}, {link[2]}, {link[3]}, {link[4]}, {link[5]}\n')
